### Site Settings ###
title               : v-kaarti
description         : >-
                      Oh hey! I'm Vijay. Welcome to my homely little corner of the internet. This is where I share my professional background, ideas, and a potpourri of events from my life.
baseurl             : "/"
repository          : v-kaarti/v-kaarti@github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true


plugins:
  - jemoji


nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md

author:
  name              : Vijay Sundarapandiyan
  image             : images/paramount-mod-final.png
  email             : vijaykaarti4@gmail.com
  facebook          : vijay.sundarapandiyan
  github            : v-kaarti
  linkedin          : vijay-sundarapandiyan


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus


### Analytics ###
analytics:
  enabled: false
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
